version: "3.3"

services:
  chrome:
    image: selenium/standalone-chrome:4.3.0-20220706
    ports:
      - "4444:4444"
  tg_bot:
    build:
      context: .
    env_file:
      - .env
    environment:
      SELENIUM_URL: "http://chrome:4444/wd/hub"
    command: python main.py
    depends_on:
      - chrome
    volumes:
      - ./src:/app/